package:
  name: nbextensions
  version: "master"

source:
  git_url: https://github.com/ipython-contrib/IPython-notebook-extensions.git
  git_tag: master 

build:
  script: python install.py
  
requirements:
  build:
    - ipython >=4
    - jupyter_client
    - jupyter_core
    - notebook
    - nbconvert
    - nbformat
    - python
    - traitlets

  run:
    - ipython >=4
    - jupyter_client
    - jupyter_core
    - notebook
    - nbconvert
    - nbformat
    - python
    - traitlets

about:
  home: https://github.com/ipython-contrib/IPython-notebook-extensions
  license:  Modified BSD License
  summary: 'Notebook extensions for the Jupyter/IPython notebook'

