package:
  name: nbextensions
  version: "4.0"

source:
  git_url: https://github.com/ipython-contrib/IPython-notebook-extensions
  git_tag: "4.0"

build:
  script: python install.py
  
requirements:
  build:
    - ipython >=4
    - jupyter-client
    - jupyter-core
    - jupyter-notebook
    - nbconvert
    - nbformat
    - python
    - traitlets

  run:
    - ipython >=4
    - jupyter-client
    - jupyter-core
    - jupyter-notebook
    - nbconvert
    - nbformat
    - python
    - traitlets

about:
  home: https://github.com/ipython-contrib/IPython-notebook-extensions
  license:  Modified BSD License
  summary: 'Notebook extensions for the IPython notebook'

